on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js version 16
      uses: actions/checkout@v2

      with:
        node-version: 16

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build and deploy to Vercel
      uses: amondnet/vercel-action
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project-id: prj_P0HmaSihpa5n5Z03pLl6zQByb28G
        build-command: npm run build
